// Code generated by entc, DO NOT EDIT.

package commute

import (
	"time"
)

const (
	// Label holds the string label denoting the commute type in the database.
	Label = "commute"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// FieldGoToWorkAt holds the string denoting the go_to_work_at field in the database.
	FieldGoToWorkAt = "go_to_work_at"
	// FieldGetOffAt holds the string denoting the get_off_at field in the database.
	FieldGetOffAt = "get_off_at"

	// Table holds the table name of the commute in the database.
	Table = "commutes"
)

// Columns holds all SQL columns for commute fields.
var Columns = []string{
	FieldID,
	FieldChannelID,
	FieldAuthorID,
	FieldGoToWorkAt,
	FieldGetOffAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGoToWorkAt holds the default value on creation for the "go_to_work_at" field.
	DefaultGoToWorkAt func() time.Time
	// DefaultGetOffAt holds the default value on creation for the "get_off_at" field.
	DefaultGetOffAt func() time.Time
)
