// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommutesColumns holds the columns for the "commutes" table.
	CommutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "author_id", Type: field.TypeString},
		{Name: "go_to_work_at", Type: field.TypeTime},
		{Name: "get_off_at", Type: field.TypeTime},
	}
	// CommutesTable holds the schema information for the "commutes" table.
	CommutesTable = &schema.Table{
		Name:        "commutes",
		Columns:     CommutesColumns,
		PrimaryKey:  []*schema.Column{CommutesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommutesTable,
	}
)

func init() {
}
