// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/aid95/zaksim-discord-bot/ent/migrate"

	"github.com/aid95/zaksim-discord-bot/ent/commute"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Commute is the client for interacting with the Commute builders.
	Commute *CommuteClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Commute = NewCommuteClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Commute: NewCommuteClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:  cfg,
		Commute: NewCommuteClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Commute.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Commute.Use(hooks...)
}

// CommuteClient is a client for the Commute schema.
type CommuteClient struct {
	config
}

// NewCommuteClient returns a client for the Commute from the given config.
func NewCommuteClient(c config) *CommuteClient {
	return &CommuteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `commute.Hooks(f(g(h())))`.
func (c *CommuteClient) Use(hooks ...Hook) {
	c.hooks.Commute = append(c.hooks.Commute, hooks...)
}

// Create returns a create builder for Commute.
func (c *CommuteClient) Create() *CommuteCreate {
	mutation := newCommuteMutation(c.config, OpCreate)
	return &CommuteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Commute entities.
func (c *CommuteClient) CreateBulk(builders ...*CommuteCreate) *CommuteCreateBulk {
	return &CommuteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Commute.
func (c *CommuteClient) Update() *CommuteUpdate {
	mutation := newCommuteMutation(c.config, OpUpdate)
	return &CommuteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CommuteClient) UpdateOne(co *Commute) *CommuteUpdateOne {
	mutation := newCommuteMutation(c.config, OpUpdateOne, withCommute(co))
	return &CommuteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CommuteClient) UpdateOneID(id int) *CommuteUpdateOne {
	mutation := newCommuteMutation(c.config, OpUpdateOne, withCommuteID(id))
	return &CommuteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Commute.
func (c *CommuteClient) Delete() *CommuteDelete {
	mutation := newCommuteMutation(c.config, OpDelete)
	return &CommuteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *CommuteClient) DeleteOne(co *Commute) *CommuteDeleteOne {
	return c.DeleteOneID(co.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *CommuteClient) DeleteOneID(id int) *CommuteDeleteOne {
	builder := c.Delete().Where(commute.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CommuteDeleteOne{builder}
}

// Query returns a query builder for Commute.
func (c *CommuteClient) Query() *CommuteQuery {
	return &CommuteQuery{config: c.config}
}

// Get returns a Commute entity by its id.
func (c *CommuteClient) Get(ctx context.Context, id int) (*Commute, error) {
	return c.Query().Where(commute.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CommuteClient) GetX(ctx context.Context, id int) *Commute {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CommuteClient) Hooks() []Hook {
	return c.hooks.Commute
}
