// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aid95/zaksim-discord-bot/ent/commute"
	"github.com/aid95/zaksim-discord-bot/ent/predicate"
)

// CommuteUpdate is the builder for updating Commute entities.
type CommuteUpdate struct {
	config
	hooks    []Hook
	mutation *CommuteMutation
}

// Where adds a new predicate for the CommuteUpdate builder.
func (cu *CommuteUpdate) Where(ps ...predicate.Commute) *CommuteUpdate {
	cu.mutation.predicates = append(cu.mutation.predicates, ps...)
	return cu
}

// SetChannelID sets the "channel_id" field.
func (cu *CommuteUpdate) SetChannelID(s string) *CommuteUpdate {
	cu.mutation.SetChannelID(s)
	return cu
}

// SetAuthorID sets the "author_id" field.
func (cu *CommuteUpdate) SetAuthorID(s string) *CommuteUpdate {
	cu.mutation.SetAuthorID(s)
	return cu
}

// SetGoToWorkAt sets the "go_to_work_at" field.
func (cu *CommuteUpdate) SetGoToWorkAt(t time.Time) *CommuteUpdate {
	cu.mutation.SetGoToWorkAt(t)
	return cu
}

// SetNillableGoToWorkAt sets the "go_to_work_at" field if the given value is not nil.
func (cu *CommuteUpdate) SetNillableGoToWorkAt(t *time.Time) *CommuteUpdate {
	if t != nil {
		cu.SetGoToWorkAt(*t)
	}
	return cu
}

// SetGetOffAt sets the "get_off_at" field.
func (cu *CommuteUpdate) SetGetOffAt(t time.Time) *CommuteUpdate {
	cu.mutation.SetGetOffAt(t)
	return cu
}

// SetNillableGetOffAt sets the "get_off_at" field if the given value is not nil.
func (cu *CommuteUpdate) SetNillableGetOffAt(t *time.Time) *CommuteUpdate {
	if t != nil {
		cu.SetGetOffAt(*t)
	}
	return cu
}

// Mutation returns the CommuteMutation object of the builder.
func (cu *CommuteUpdate) Mutation() *CommuteMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommuteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommuteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommuteUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommuteUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommuteUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CommuteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   commute.Table,
			Columns: commute.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: commute.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.ChannelID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: commute.FieldChannelID,
		})
	}
	if value, ok := cu.mutation.AuthorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: commute.FieldAuthorID,
		})
	}
	if value, ok := cu.mutation.GoToWorkAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: commute.FieldGoToWorkAt,
		})
	}
	if value, ok := cu.mutation.GetOffAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: commute.FieldGetOffAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commute.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CommuteUpdateOne is the builder for updating a single Commute entity.
type CommuteUpdateOne struct {
	config
	hooks    []Hook
	mutation *CommuteMutation
}

// SetChannelID sets the "channel_id" field.
func (cuo *CommuteUpdateOne) SetChannelID(s string) *CommuteUpdateOne {
	cuo.mutation.SetChannelID(s)
	return cuo
}

// SetAuthorID sets the "author_id" field.
func (cuo *CommuteUpdateOne) SetAuthorID(s string) *CommuteUpdateOne {
	cuo.mutation.SetAuthorID(s)
	return cuo
}

// SetGoToWorkAt sets the "go_to_work_at" field.
func (cuo *CommuteUpdateOne) SetGoToWorkAt(t time.Time) *CommuteUpdateOne {
	cuo.mutation.SetGoToWorkAt(t)
	return cuo
}

// SetNillableGoToWorkAt sets the "go_to_work_at" field if the given value is not nil.
func (cuo *CommuteUpdateOne) SetNillableGoToWorkAt(t *time.Time) *CommuteUpdateOne {
	if t != nil {
		cuo.SetGoToWorkAt(*t)
	}
	return cuo
}

// SetGetOffAt sets the "get_off_at" field.
func (cuo *CommuteUpdateOne) SetGetOffAt(t time.Time) *CommuteUpdateOne {
	cuo.mutation.SetGetOffAt(t)
	return cuo
}

// SetNillableGetOffAt sets the "get_off_at" field if the given value is not nil.
func (cuo *CommuteUpdateOne) SetNillableGetOffAt(t *time.Time) *CommuteUpdateOne {
	if t != nil {
		cuo.SetGetOffAt(*t)
	}
	return cuo
}

// Mutation returns the CommuteMutation object of the builder.
func (cuo *CommuteUpdateOne) Mutation() *CommuteMutation {
	return cuo.mutation
}

// Save executes the query and returns the updated Commute entity.
func (cuo *CommuteUpdateOne) Save(ctx context.Context) (*Commute, error) {
	var (
		err  error
		node *Commute
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommuteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommuteUpdateOne) SaveX(ctx context.Context) *Commute {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommuteUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommuteUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CommuteUpdateOne) sqlSave(ctx context.Context) (_node *Commute, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   commute.Table,
			Columns: commute.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: commute.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Commute.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.ChannelID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: commute.FieldChannelID,
		})
	}
	if value, ok := cuo.mutation.AuthorID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: commute.FieldAuthorID,
		})
	}
	if value, ok := cuo.mutation.GoToWorkAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: commute.FieldGoToWorkAt,
		})
	}
	if value, ok := cuo.mutation.GetOffAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: commute.FieldGetOffAt,
		})
	}
	_node = &Commute{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commute.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
