// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/aid95/zaksim-discord-bot/ent/commute"
	"github.com/aid95/zaksim-discord-bot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commuteFields := schema.Commute{}.Fields()
	_ = commuteFields
	// commuteDescGoToWorkAt is the schema descriptor for go_to_work_at field.
	commuteDescGoToWorkAt := commuteFields[2].Descriptor()
	// commute.DefaultGoToWorkAt holds the default value on creation for the go_to_work_at field.
	commute.DefaultGoToWorkAt = commuteDescGoToWorkAt.Default.(func() time.Time)
	// commuteDescGetOffAt is the schema descriptor for get_off_at field.
	commuteDescGetOffAt := commuteFields[3].Descriptor()
	// commute.DefaultGetOffAt holds the default value on creation for the get_off_at field.
	commute.DefaultGetOffAt = commuteDescGetOffAt.Default.(func() time.Time)
}
